### PR TITLE
Proofread README

### PR DESCRIPTION
**Pull request by DeflateAwning**

### CODE REVIEW

**Review by jortbmd — APPROVED** [review]
Thanks for looking at it. Looks better, will merge!

**Comment by DeflateAwning** [comment]
Awesome, thanks a lot!

**Comment by DeflateAwning** [comment]
I did a couple other tiny edits on the command labels

**Comment by DeflateAwning** [comment]
Would really appreciate if you could merge this and tag a super minor release. Would really help drive home that this is a quality extension as I work on getting more people into it, including some people who may help with feature requests!

**Pull request merged**
